/*
 *  Copyright 2025 Chris Margonis
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

package com.ultimus.distantworlds.theme

import androidx.compose.ui.graphics.Color

val primaryLight: Color = Color(0xFF653CA6)
val onPrimaryLight: Color = Color(0xFFFFFFFF)
val primaryContainerLight: Color = Color(0xFF7E56C1)
val onPrimaryContainerLight: Color = Color(0xFFF5EAFF)
val secondaryLight: Color = Color(0xFF675781)
val onSecondaryLight: Color = Color(0xFFFFFFFF)
val secondaryContainerLight: Color = Color(0xFFE0CCFE)
val onSecondaryContainerLight: Color = Color(0xFF64547E)
val tertiaryLight: Color = Color(0xFF8F2D6A)
val onTertiaryLight: Color = Color(0xFFFFFFFF)
val tertiaryContainerLight: Color = Color(0xFFAD4684)
val onTertiaryContainerLight: Color = Color(0xFFFFE9F1)
val errorLight: Color = Color(0xFFBA1A1A)
val onErrorLight: Color = Color(0xFFFFFFFF)
val errorContainerLight: Color = Color(0xFFFFDAD6)
val onErrorContainerLight: Color = Color(0xFF93000A)
val backgroundLight: Color = Color(0xFFFEF7FF)
val onBackgroundLight: Color = Color(0xFF1D1A21)
val surfaceLight: Color = Color(0xFFFEF7FF)
val onSurfaceLight: Color = Color(0xFF1D1A21)
val surfaceVariantLight: Color = Color(0xFFE9DFF0)
val onSurfaceVariantLight: Color = Color(0xFF4A4452)
val outlineLight: Color = Color(0xFF7B7483)
val outlineVariantLight: Color = Color(0xFFCCC3D3)
val scrimLight: Color = Color(0xFF000000)
val inverseSurfaceLight: Color = Color(0xFF322F36)
val inverseOnSurfaceLight: Color = Color(0xFFF6EEF8)
val inversePrimaryLight: Color = Color(0xFFD5BBFF)
val surfaceDimLight: Color = Color(0xFFDFD8E1)
val surfaceBrightLight: Color = Color(0xFFFEF7FF)
val surfaceContainerLowestLight: Color = Color(0xFFFFFFFF)
val surfaceContainerLowLight: Color = Color(0xFFF9F1FB)
val surfaceContainerLight: Color = Color(0xFFF3EBF5)
val surfaceContainerHighLight: Color = Color(0xFFEDE6F0)
val surfaceContainerHighestLight: Color = Color(0xFFE7E0EA)

val primaryLightMediumContrast: Color = Color(0xFF461887)
val onPrimaryLightMediumContrast: Color = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast: Color = Color(0xFF7E56C1)
val onPrimaryContainerLightMediumContrast: Color = Color(0xFFFFFFFF)
val secondaryLightMediumContrast: Color = Color(0xFF3D2F57)
val onSecondaryLightMediumContrast: Color = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast: Color = Color(0xFF766591)
val onSecondaryContainerLightMediumContrast: Color = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast: Color = Color(0xFF69084B)
val onTertiaryLightMediumContrast: Color = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast: Color = Color(0xFFAD4684)
val onTertiaryContainerLightMediumContrast: Color = Color(0xFFFFFFFF)
val errorLightMediumContrast: Color = Color(0xFF740006)
val onErrorLightMediumContrast: Color = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast: Color = Color(0xFFCF2C27)
val onErrorContainerLightMediumContrast: Color = Color(0xFFFFFFFF)
val backgroundLightMediumContrast: Color = Color(0xFFFEF7FF)
val onBackgroundLightMediumContrast: Color = Color(0xFF1D1A21)
val surfaceLightMediumContrast: Color = Color(0xFFFEF7FF)
val onSurfaceLightMediumContrast: Color = Color(0xFF131017)
val surfaceVariantLightMediumContrast: Color = Color(0xFFE9DFF0)
val onSurfaceVariantLightMediumContrast: Color = Color(0xFF393441)
val outlineLightMediumContrast: Color = Color(0xFF56505E)
val outlineVariantLightMediumContrast: Color = Color(0xFF716A79)
val scrimLightMediumContrast: Color = Color(0xFF000000)
val inverseSurfaceLightMediumContrast: Color = Color(0xFF322F36)
val inverseOnSurfaceLightMediumContrast: Color = Color(0xFFF6EEF8)
val inversePrimaryLightMediumContrast: Color = Color(0xFFD5BBFF)
val surfaceDimLightMediumContrast: Color = Color(0xFFCBC4CE)
val surfaceBrightLightMediumContrast: Color = Color(0xFFFEF7FF)
val surfaceContainerLowestLightMediumContrast: Color = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast: Color = Color(0xFFF9F1FB)
val surfaceContainerLightMediumContrast: Color = Color(0xFFEDE6F0)
val surfaceContainerHighLightMediumContrast: Color = Color(0xFFE2DAE4)
val surfaceContainerHighestLightMediumContrast: Color = Color(0xFFD6CFD9)

val primaryLightHighContrast: Color = Color(0xFF3B057D)
val onPrimaryLightHighContrast: Color = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast: Color = Color(0xFF5A309B)
val onPrimaryContainerLightHighContrast: Color = Color(0xFFFFFFFF)
val secondaryLightHighContrast: Color = Color(0xFF33254C)
val onSecondaryLightHighContrast: Color = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast: Color = Color(0xFF51426B)
val onSecondaryContainerLightHighContrast: Color = Color(0xFFFFFFFF)
val tertiaryLightHighContrast: Color = Color(0xFF5A003F)
val onTertiaryLightHighContrast: Color = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast: Color = Color(0xFF82215F)
val onTertiaryContainerLightHighContrast: Color = Color(0xFFFFFFFF)
val errorLightHighContrast: Color = Color(0xFF600004)
val onErrorLightHighContrast: Color = Color(0xFFFFFFFF)
val errorContainerLightHighContrast: Color = Color(0xFF98000A)
val onErrorContainerLightHighContrast: Color = Color(0xFFFFFFFF)
val backgroundLightHighContrast: Color = Color(0xFFFEF7FF)
val onBackgroundLightHighContrast: Color = Color(0xFF1D1A21)
val surfaceLightHighContrast: Color = Color(0xFFFEF7FF)
val onSurfaceLightHighContrast: Color = Color(0xFF000000)
val surfaceVariantLightHighContrast: Color = Color(0xFFE9DFF0)
val onSurfaceVariantLightHighContrast: Color = Color(0xFF000000)
val outlineLightHighContrast: Color = Color(0xFF2F2A36)
val outlineVariantLightHighContrast: Color = Color(0xFF4D4754)
val scrimLightHighContrast: Color = Color(0xFF000000)
val inverseSurfaceLightHighContrast: Color = Color(0xFF322F36)
val inverseOnSurfaceLightHighContrast: Color = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast: Color = Color(0xFFD5BBFF)
val surfaceDimLightHighContrast: Color = Color(0xFFBDB7C0)
val surfaceBrightLightHighContrast: Color = Color(0xFFFEF7FF)
val surfaceContainerLowestLightHighContrast: Color = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast: Color = Color(0xFFF6EEF8)
val surfaceContainerLightHighContrast: Color = Color(0xFFE7E0EA)
val surfaceContainerHighLightHighContrast: Color = Color(0xFFD9D2DC)
val surfaceContainerHighestLightHighContrast: Color = Color(0xFFCBC4CE)

val primaryDark: Color = Color(0xFFD5BBFF)
val onPrimaryDark: Color = Color(0xFF400E81)
val primaryContainerDark: Color = Color(0xFF7E56C1)
val onPrimaryContainerDark: Color = Color(0xFFF5EAFF)
val secondaryDark: Color = Color(0xFFD2BEEF)
val onSecondaryDark: Color = Color(0xFF382950)
val secondaryContainerDark: Color = Color(0xFF4F3F68)
val onSecondaryContainerDark: Color = Color(0xFFC0ADDD)
val tertiaryDark: Color = Color(0xFFFFAFD8)
val onTertiaryDark: Color = Color(0xFF610045)
val tertiaryContainerDark: Color = Color(0xFFAD4684)
val onTertiaryContainerDark: Color = Color(0xFFFFE9F1)
val errorDark: Color = Color(0xFFFFB4AB)
val onErrorDark: Color = Color(0xFF690005)
val errorContainerDark: Color = Color(0xFF93000A)
val onErrorContainerDark: Color = Color(0xFFFFDAD6)
val backgroundDark: Color = Color(0xFF151219)
val onBackgroundDark: Color = Color(0xFFE7E0EA)
val surfaceDark: Color = Color(0xFF151219)
val onSurfaceDark: Color = Color(0xFFE7E0EA)
val surfaceVariantDark: Color = Color(0xFF4A4452)
val onSurfaceVariantDark: Color = Color(0xFFCCC3D3)
val outlineDark: Color = Color(0xFF958E9D)
val outlineVariantDark: Color = Color(0xFF4A4452)
val scrimDark: Color = Color(0xFF000000)
val inverseSurfaceDark: Color = Color(0xFFE7E0EA)
val inverseOnSurfaceDark: Color = Color(0xFF322F36)
val inversePrimaryDark: Color = Color(0xFF7048B2)
val surfaceDimDark: Color = Color(0xFF151219)
val surfaceBrightDark: Color = Color(0xFF3B383F)
val surfaceContainerLowestDark: Color = Color(0xFF100D13)
val surfaceContainerLowDark: Color = Color(0xFF1D1A21)
val surfaceContainerDark: Color = Color(0xFF211E25)
val surfaceContainerHighDark: Color = Color(0xFF2C2930)
val surfaceContainerHighestDark: Color = Color(0xFF37333B)

val primaryDarkMediumContrast: Color = Color(0xFFE7D5FF)
val onPrimaryDarkMediumContrast: Color = Color(0xFF340070)
val primaryContainerDarkMediumContrast: Color = Color(0xFFA47CE9)
val onPrimaryContainerDarkMediumContrast: Color = Color(0xFF000000)
val secondaryDarkMediumContrast: Color = Color(0xFFE7D5FF)
val onSecondaryDarkMediumContrast: Color = Color(0xFF2C1E45)
val secondaryContainerDarkMediumContrast: Color = Color(0xFF9B89B7)
val onSecondaryContainerDarkMediumContrast: Color = Color(0xFF000000)
val tertiaryDarkMediumContrast: Color = Color(0xFFFFCFE5)
val onTertiaryDarkMediumContrast: Color = Color(0xFF4E0036)
val tertiaryContainerDarkMediumContrast: Color = Color(0xFFD96AAA)
val onTertiaryContainerDarkMediumContrast: Color = Color(0xFF000000)
val errorDarkMediumContrast: Color = Color(0xFFFFD2CC)
val onErrorDarkMediumContrast: Color = Color(0xFF540003)
val errorContainerDarkMediumContrast: Color = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast: Color = Color(0xFF000000)
val backgroundDarkMediumContrast: Color = Color(0xFF151219)
val onBackgroundDarkMediumContrast: Color = Color(0xFFE7E0EA)
val surfaceDarkMediumContrast: Color = Color(0xFF151219)
val onSurfaceDarkMediumContrast: Color = Color(0xFFFFFFFF)
val surfaceVariantDarkMediumContrast: Color = Color(0xFF4A4452)
val onSurfaceVariantDarkMediumContrast: Color = Color(0xFFE2D9EA)
val outlineDarkMediumContrast: Color = Color(0xFFB7AFBF)
val outlineVariantDarkMediumContrast: Color = Color(0xFF958D9D)
val scrimDarkMediumContrast: Color = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast: Color = Color(0xFFE7E0EA)
val inverseOnSurfaceDarkMediumContrast: Color = Color(0xFF2C2930)
val inversePrimaryDarkMediumContrast: Color = Color(0xFF582F9A)
val surfaceDimDarkMediumContrast: Color = Color(0xFF151219)
val surfaceBrightDarkMediumContrast: Color = Color(0xFF47434B)
val surfaceContainerLowestDarkMediumContrast: Color = Color(0xFF08060C)
val surfaceContainerLowDarkMediumContrast: Color = Color(0xFF1F1C23)
val surfaceContainerDarkMediumContrast: Color = Color(0xFF2A262E)
val surfaceContainerHighDarkMediumContrast: Color = Color(0xFF353139)
val surfaceContainerHighestDarkMediumContrast: Color = Color(0xFF403C44)

val primaryDarkHighContrast: Color = Color(0xFFF7ECFF)
val onPrimaryDarkHighContrast: Color = Color(0xFF000000)
val primaryContainerDarkHighContrast: Color = Color(0xFFD2B6FF)
val onPrimaryContainerDarkHighContrast: Color = Color(0xFF120030)
val secondaryDarkHighContrast: Color = Color(0xFFF7ECFF)
val onSecondaryDarkHighContrast: Color = Color(0xFF000000)
val secondaryContainerDarkHighContrast: Color = Color(0xFFCEBAEB)
val onSecondaryContainerDarkHighContrast: Color = Color(0xFF110329)
val tertiaryDarkHighContrast: Color = Color(0xFFFFEBF2)
val onTertiaryDarkHighContrast: Color = Color(0xFF000000)
val tertiaryContainerDarkHighContrast: Color = Color(0xFFFFA8D6)
val onTertiaryContainerDarkHighContrast: Color = Color(0xFF1F0013)
val errorDarkHighContrast: Color = Color(0xFFFFECE9)
val onErrorDarkHighContrast: Color = Color(0xFF000000)
val errorContainerDarkHighContrast: Color = Color(0xFFFFAEA4)
val onErrorContainerDarkHighContrast: Color = Color(0xFF220001)
val backgroundDarkHighContrast: Color = Color(0xFF151219)
val onBackgroundDarkHighContrast: Color = Color(0xFFE7E0EA)
val surfaceDarkHighContrast: Color = Color(0xFF151219)
val onSurfaceDarkHighContrast: Color = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast: Color = Color(0xFF4A4452)
val onSurfaceVariantDarkHighContrast: Color = Color(0xFFFFFFFF)
val outlineDarkHighContrast: Color = Color(0xFFF6ECFD)
val outlineVariantDarkHighContrast: Color = Color(0xFFC8BFD0)
val scrimDarkHighContrast: Color = Color(0xFF000000)
val inverseSurfaceDarkHighContrast: Color = Color(0xFFE7E0EA)
val inverseOnSurfaceDarkHighContrast: Color = Color(0xFF000000)
val inversePrimaryDarkHighContrast: Color = Color(0xFF582F9A)
val surfaceDimDarkHighContrast: Color = Color(0xFF151219)
val surfaceBrightDarkHighContrast: Color = Color(0xFF534E56)
val surfaceContainerLowestDarkHighContrast: Color = Color(0xFF000000)
val surfaceContainerLowDarkHighContrast: Color = Color(0xFF211E25)
val surfaceContainerDarkHighContrast: Color = Color(0xFF322F36)
val surfaceContainerHighDarkHighContrast: Color = Color(0xFF3E3A42)
val surfaceContainerHighestDarkHighContrast: Color = Color(0xFF49454D)
