name: Pull Request Automation

on:
  pull_request:
    types: [ opened, closed, ready_for_review, reopened ]

jobs:

  # Add labels based on branch name
  add-branch-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Add branch labels
        if: ${{ github.event.action == 'opened' }}
        uses: TimonVS/pr-labeler-action@v5
        with:
          configuration-path: .github/pull-request-labels.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Add pull request status-indicating labels
  add-status-label:
    runs-on: ubuntu-latest
    steps:
      - name: Add WIP label
        if: ${{ github.event.action == 'opened' && github.event.pull_request.draft }}
        uses: actions/github-script@v7
        with:
          github-token: ${{github.token}}
          script: |
            github.action.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.number,
              labels: ['WIP']
            })
